version: "2"
#if needed to map the orthancPACS to a different hard disk device (after mounting it in path)
# volumes: ["/home/petctviewer/orthanc:/var/lib/orthanc/db:Z"]

networks:
  web:
    external: true
  internal:
    external: false

services:

    orthanctoolsjs:
        build: .
        image: my-orthanctoolsjs
        container_name: orthanctoolsjs
        restart: unless-stopped
        volumes: ["./data/orthanctoolsjs:/OrthancToolsJs/data:Z"]
        environment:
            TZ: "Asia/Ho_Chi_Minh"
            ORTHANC_ADDRESS: "http://orthanc"
            ORTHANC_PORT: "8042"
            ORTHANC_USERNAME: "salim"
            ORTHANC_PASSWORD: "salim"
            # DOMAIN_PROTOCOL: "https"
            # DOMAIN_ADDRESS: "0e44be91-4285-440b-a132-c6580851eed7.pub.instances.scw.cloud"
            REDIS_HOST: "redis"
            REDIS_PORT: "6379"
            REDIS_PASSWORD: ""
            DB_USERNAME: "postgres"
            DB_PASSWORD: "postgres"
            DB_HOST: "postgres"
            DB_PORT: "5432"
            DB_NAME: orthanctoolsjs
        networks:
          - internal
          - web
        ports: ["4000:4000"]
        labels:
        - "traefik.enable=true"
        - "traefik.port=4000"
        # - "traefik.http.routers.blog.rule=Host(`0e44be91-4285-440b-a132-c6580851eed7.pub.instances.scw.cloud`)"
        # - "traefik.http.routers.blog.entrypoints=websecure"
        - "traefik.docker.network=web"  
    
    redis:
        image: redis:alpine
        networks:
          - internal


    postgres:
        container_name: postgres
        image: postgres:13.1
        networks:
          - internal
        environment:
            POSTGRES_DB : "orthanctoolsjs"
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        restart: unless-stopped

    orthanc:
        image: osimis/orthanc:21.1.7
        container_name: orthanc
        restart: unless-stopped
        ports: ["8042:8042"]
        volumes: ["./data/orthanc:/var/lib/orthanc:Z"]
        networks:
          - internal
        environment:
            ORTHANC__NAME: "OrthancToolsJS"
            ORTHANC__DICOM_SERVER_ENABLED: "true"
            ORTHANC__DICOM_MODALITIES_IN_DATABASE: "true"
            ORTHANC__DATABASE_SERVER_IDENTIFIER : "Orthanc1"
            ORTHANC__ORTHANC_PEERS_IN_DATABASE: "true"
            DICOM_WEB_PLUGIN_ENABLED: "true"
            OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
            PYTHON_PLUGIN_ENABLED: "true"
            TRANSFERS_PLUGIN_ENABLED: "true"
            WORKLISTS_PLUGIN_ENABLED: "true"
            ORTHANC__REGISTERED_USERS: |
                {"salim": "salim"}
            ORTHANC__DICOM_WEB__ENABLE: "true"
            ORTHANC__DICOM_WEB__ROOT: "/dicom-web/"
            ORTHANC__DICOM_WEB__ENABLEWADO: "true"
            ORTHANC__DICOM_WEB__WADOROOT: "/wado"
            ORTHANC__DICOM_WEB__SSL: "true"
            ORTHANC__DICOM_WEB__STUDIESMETADATA: "MainDicomTags"
            ORTHANC__DICOM_WEB__SERIESMETADATA: "Full"

    orthanctoolsjspacs:
        image: osimis/orthanc:21.1.7
        ports: ["4245:4842"]
        container_name: orthanctoolsjspacs
        restart: unless-stopped
        volumes: ["./data/orthancpacs:/var/lib/orthanc:Z"]
        networks:
          - internal
        environment:
            ORTHANC__NAME: "OrthancPacs"
            ORTHANC__HTTP_PORT: "8642"
            ORTHANC__DICOM_PORT: "4842"
            ORTHANC__DICOM_MODALITIES_IN_DATABASE: "true"
            ORTHANC__DICOM_ALWAYS_ALLOW_FIND: "true"
            ORTHANC__REGISTERED_USERS: |
                    {"salim": "salim"}

    ris:
        build: ./ris-docker/
        image: ris
        container_name: ris
        restart: unless-stopped
        ports: ["5000:5000"]
        volumes: 
          - "./data/ris:/RIS/static/:Z"
          - "./data/cbir_feature:/RIS/cbir_feature/:Z"
        networks:
          - internal
          - web
        environment:
            PORT: 5000
            SECRET_KEY: '123456'
            DB_URI: 'postgresql://postgres:postgres@postgres:5432/orthanctoolsjs'
            MAIL_USERNAME: "nguyenminhhieu.it1.k52@gmail.com"
            MAIL_PASSWORD: "yxicljxtkzxrxbvv"
            ADMIN_USERNAME: "itsme"
            ADMIN_EMAIL: "itsme@A.com"
            ADMIN_PWD: "123456"
            ORTHANC_USERNAME: "salim"
            ORTHANC_PWD: "salim"





# volumes:
#         orthanc:
#         orthancpacs:
#         orthanctoolsjs:
#         postgres:
#         ris:
